-- ============================================================================
-- Multi-Agent Debate System - Master Setup Script
-- ============================================================================
-- Run this script to set up all Snowflake objects for the debate system.
-- Prerequisites: ACCOUNTADMIN role or equivalent permissions
-- ============================================================================

-- Set context
USE ROLE ACCOUNTADMIN;

-- ============================================================================
-- STEP 1: Database and Warehouse Setup
-- ============================================================================
!print 'Step 1: Creating database and warehouse...'

CREATE WAREHOUSE IF NOT EXISTS COMPUTE_WH
    WAREHOUSE_SIZE = 'SMALL'
    AUTO_SUSPEND = 300
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS FINANCIAL_RESEARCH;
CREATE SCHEMA IF NOT EXISTS FINANCIAL_RESEARCH.EQUITY_RESEARCH;

USE WAREHOUSE COMPUTE_WH;
USE DATABASE FINANCIAL_RESEARCH;
USE SCHEMA EQUITY_RESEARCH;

-- ============================================================================
-- STEP 2: Create Tables
-- ============================================================================
!print 'Step 2: Creating tables...'

-- Investment Metrics
CREATE OR REPLACE TABLE INVESTMENT_METRICS (
    TICKER VARCHAR(10) NOT NULL,
    COMPANY_NAME VARCHAR(200) NOT NULL,
    METRIC_DATE DATE NOT NULL,
    PE_RATIO FLOAT, FORWARD_PE FLOAT, PEG_RATIO FLOAT,
    PRICE_TO_BOOK FLOAT, PRICE_TO_SALES FLOAT, EV_TO_EBITDA FLOAT,
    ROE_PCT FLOAT, ROA_PCT FLOAT,
    GROSS_MARGIN_PCT FLOAT, OPERATING_MARGIN_PCT FLOAT, NET_MARGIN_PCT FLOAT,
    DEBT_TO_EQUITY FLOAT, CURRENT_RATIO FLOAT, QUICK_RATIO FLOAT,
    DIVIDEND_YIELD_PCT FLOAT, PAYOUT_RATIO_PCT FLOAT,
    REVENUE_GROWTH_YOY_PCT FLOAT, EARNINGS_GROWTH_YOY_PCT FLOAT,
    MARKET_CAP_BILLIONS FLOAT, ENTERPRISE_VALUE_BILLIONS FLOAT,
    SHARES_OUTSTANDING_MILLIONS FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (TICKER, METRIC_DATE)
);

-- Earnings History
CREATE OR REPLACE TABLE EARNINGS_HISTORY (
    TICKER VARCHAR(10) NOT NULL,
    COMPANY_NAME VARCHAR(200) NOT NULL,
    FISCAL_QUARTER VARCHAR(10) NOT NULL,
    FISCAL_YEAR INT NOT NULL,
    REPORT_DATE DATE NOT NULL,
    EPS_ACTUAL FLOAT, EPS_ESTIMATE FLOAT, EPS_SURPRISE FLOAT, EPS_SURPRISE_PCT FLOAT,
    REVENUE_ACTUAL_MILLIONS FLOAT, REVENUE_ESTIMATE_MILLIONS FLOAT,
    REVENUE_SURPRISE_MILLIONS FLOAT, REVENUE_SURPRISE_PCT FLOAT,
    BEAT_MISS VARCHAR(10),
    GUIDANCE_EPS_LOW FLOAT, GUIDANCE_EPS_HIGH FLOAT,
    REPORT_TIME VARCHAR(20),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (TICKER, FISCAL_YEAR, FISCAL_QUARTER)
);

-- Technical Indicators
CREATE OR REPLACE TABLE TECHNICAL_INDICATORS (
    TICKER VARCHAR(10) NOT NULL,
    INDICATOR_DATE DATE NOT NULL,
    OPEN_PRICE FLOAT, HIGH_PRICE FLOAT, LOW_PRICE FLOAT,
    CLOSE_PRICE FLOAT, ADJUSTED_CLOSE FLOAT, VOLUME BIGINT,
    SMA_5 FLOAT, SMA_10 FLOAT, SMA_20 FLOAT, SMA_50 FLOAT, SMA_200 FLOAT,
    EMA_12 FLOAT, EMA_26 FLOAT,
    RSI_14 FLOAT, RSI_SIGNAL VARCHAR(20),
    MACD FLOAT, MACD_SIGNAL FLOAT, MACD_HISTOGRAM FLOAT,
    BOLLINGER_UPPER FLOAT, BOLLINGER_MIDDLE FLOAT, BOLLINGER_LOWER FLOAT,
    ATR_14 FLOAT, VOLATILITY_20D FLOAT, ADX_14 FLOAT,
    TREND_STRENGTH VARCHAR(20),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (TICKER, INDICATOR_DATE)
);

-- Market Sentiment
CREATE OR REPLACE TABLE MARKET_SENTIMENT (
    TICKER VARCHAR(10) NOT NULL,
    COMPANY_NAME VARCHAR(200) NOT NULL,
    SENTIMENT_DATE DATE NOT NULL,
    NEWS_SENTIMENT_SCORE FLOAT, NEWS_ARTICLE_COUNT INT,
    SOCIAL_MEDIA_SENTIMENT_SCORE FLOAT, SOCIAL_MENTION_COUNT INT,
    OVERALL_SENTIMENT VARCHAR(20),
    BULLISH_PCT FLOAT, BEARISH_PCT FLOAT, NEUTRAL_PCT FLOAT,
    ANALYST_RATING_AVG FLOAT, ANALYST_RATING_COUNT INT,
    PRICE_TARGET_AVG FLOAT, PRICE_TARGET_HIGH FLOAT, PRICE_TARGET_LOW FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (TICKER, SENTIMENT_DATE)
);

-- Insider Transactions
CREATE OR REPLACE TABLE INSIDER_TRANSACTIONS (
    TRANSACTION_ID VARCHAR(50) NOT NULL,
    TICKER VARCHAR(10) NOT NULL,
    COMPANY_NAME VARCHAR(200) NOT NULL,
    INSIDER_NAME VARCHAR(200) NOT NULL,
    INSIDER_TITLE VARCHAR(200),
    TRANSACTION_TYPE VARCHAR(50) NOT NULL,
    TRANSACTION_DATE DATE NOT NULL,
    SHARES_TRADED BIGINT,
    PRICE_PER_SHARE FLOAT,
    TOTAL_VALUE FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (TRANSACTION_ID)
);

-- Institutional Holdings
CREATE OR REPLACE TABLE INSTITUTIONAL_HOLDINGS (
    HOLDING_ID VARCHAR(50) NOT NULL,
    TICKER VARCHAR(10) NOT NULL,
    COMPANY_NAME VARCHAR(200) NOT NULL,
    INSTITUTION_NAME VARCHAR(300) NOT NULL,
    INSTITUTION_TYPE VARCHAR(100),
    REPORT_DATE DATE NOT NULL,
    SHARES_HELD BIGINT,
    VALUE_USD_MILLIONS FLOAT,
    PERCENT_OF_SHARES_OUTSTANDING FLOAT,
    CHANGE_TYPE VARCHAR(20),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (HOLDING_ID)
);

-- Analyst Reports (for Cortex Search)
CREATE OR REPLACE TABLE ANALYST_REPORTS (
    REPORT_ID VARCHAR(50) NOT NULL,
    TICKER VARCHAR(10) NOT NULL,
    COMPANY_NAME VARCHAR(200) NOT NULL,
    FIRM VARCHAR(200) NOT NULL,
    ANALYST_NAME VARCHAR(200),
    REPORT_DATE DATE NOT NULL,
    REPORT_TITLE VARCHAR(500),
    REPORT_TYPE VARCHAR(50),
    RATING VARCHAR(50),
    PRICE_TARGET FLOAT,
    REPORT_SUMMARY VARCHAR(5000),
    REPORT_CONTENT VARCHAR(65535),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (REPORT_ID)
);

-- Earnings Transcripts (for Cortex Search)
CREATE OR REPLACE TABLE EARNINGS_TRANSCRIPTS (
    TRANSCRIPT_ID VARCHAR(50) NOT NULL,
    TICKER VARCHAR(10) NOT NULL,
    COMPANY_NAME VARCHAR(200) NOT NULL,
    CALL_DATE TIMESTAMP_NTZ NOT NULL,
    FISCAL_QUARTER VARCHAR(10),
    FISCAL_YEAR INT,
    CALL_TYPE VARCHAR(50),
    CEO_NAME VARCHAR(200),
    CFO_NAME VARCHAR(200),
    TRANSCRIPT_TITLE VARCHAR(500),
    TRANSCRIPT_SUMMARY VARCHAR(5000),
    TRANSCRIPT_CONTENT VARCHAR(65535),
    OVERALL_TONE VARCHAR(50),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (TRANSCRIPT_ID)
);

-- SEC Filings (for Cortex Search)
CREATE OR REPLACE TABLE SEC_FILINGS (
    FILING_ID VARCHAR(50) NOT NULL,
    TICKER VARCHAR(10) NOT NULL,
    COMPANY_NAME VARCHAR(200) NOT NULL,
    FILING_TYPE VARCHAR(20) NOT NULL,
    FILING_DATE DATE NOT NULL,
    FILING_TITLE VARCHAR(500),
    FILING_CONTENT VARCHAR(65535),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (FILING_ID)
);

-- Annual Reports (for Cortex Search)
CREATE OR REPLACE TABLE ANNUAL_REPORTS (
    REPORT_ID VARCHAR(50) NOT NULL,
    TICKER VARCHAR(10) NOT NULL,
    COMPANY_NAME VARCHAR(200) NOT NULL,
    FISCAL_YEAR INT NOT NULL,
    REPORT_DATE DATE NOT NULL,
    REPORT_TITLE VARCHAR(500),
    REPORT_CONTENT VARCHAR(65535),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (REPORT_ID)
);

!print 'Tables created successfully.'

-- ============================================================================
-- STEP 3: Create Stage for Semantic Model
-- ============================================================================
!print 'Step 3: Creating semantic model stage...'

CREATE OR REPLACE STAGE SEMANTIC_MODELS
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Stage for Cortex Analyst semantic model files';

-- Upload semantic model (run separately):
-- PUT file://config/financial_research_semantic_model.yaml @SEMANTIC_MODELS AUTO_COMPRESS=FALSE;

!print 'Stage created. Upload semantic model with: PUT file://config/financial_research_semantic_model.yaml @SEMANTIC_MODELS AUTO_COMPRESS=FALSE;'

-- ============================================================================
-- STEP 4: Create Cortex Search Services
-- ============================================================================
!print 'Step 4: Creating Cortex Search services...'

-- Analyst Reports Search
CREATE OR REPLACE CORTEX SEARCH SERVICE ANALYST_REPORTS_SEARCH
    ON REPORT_CONTENT
    ATTRIBUTES TICKER, COMPANY_NAME, FIRM, ANALYST_NAME, RATING, PRICE_TARGET, REPORT_TITLE, REPORT_DATE
    WAREHOUSE = COMPUTE_WH
    TARGET_LAG = '1 hour'
AS (
    SELECT REPORT_ID, TICKER, COMPANY_NAME, FIRM, ANALYST_NAME, RATING, PRICE_TARGET,
           REPORT_DATE, REPORT_TITLE, REPORT_TYPE, REPORT_CONTENT
    FROM ANALYST_REPORTS WHERE REPORT_CONTENT IS NOT NULL
);

-- Earnings Transcripts Search
CREATE OR REPLACE CORTEX SEARCH SERVICE EARNINGS_TRANSCRIPTS_SEARCH
    ON TRANSCRIPT_CONTENT
    ATTRIBUTES TICKER, COMPANY_NAME, FISCAL_QUARTER, FISCAL_YEAR, CALL_DATE, TRANSCRIPT_TITLE
    WAREHOUSE = COMPUTE_WH
    TARGET_LAG = '1 hour'
AS (
    SELECT TRANSCRIPT_ID, TICKER, COMPANY_NAME, FISCAL_QUARTER, FISCAL_YEAR,
           CALL_DATE, TRANSCRIPT_TITLE, CALL_TYPE, OVERALL_TONE, TRANSCRIPT_CONTENT
    FROM EARNINGS_TRANSCRIPTS WHERE TRANSCRIPT_CONTENT IS NOT NULL
);

-- SEC Filings Search
CREATE OR REPLACE CORTEX SEARCH SERVICE SEC_FILINGS_SEARCH
    ON FILING_CONTENT
    ATTRIBUTES TICKER, COMPANY_NAME, FILING_TYPE, FILING_DATE, FILING_TITLE
    WAREHOUSE = COMPUTE_WH
    TARGET_LAG = '1 hour'
AS (
    SELECT FILING_ID, TICKER, COMPANY_NAME, FILING_TYPE, FILING_DATE, FILING_TITLE, FILING_CONTENT
    FROM SEC_FILINGS WHERE FILING_CONTENT IS NOT NULL
);

-- Annual Reports Search
CREATE OR REPLACE CORTEX SEARCH SERVICE ANNUAL_REPORTS_SEARCH
    ON REPORT_CONTENT
    ATTRIBUTES TICKER, COMPANY_NAME, FISCAL_YEAR, REPORT_DATE, REPORT_TITLE
    WAREHOUSE = COMPUTE_WH
    TARGET_LAG = '1 hour'
AS (
    SELECT REPORT_ID, TICKER, COMPANY_NAME, FISCAL_YEAR, REPORT_DATE, REPORT_TITLE, REPORT_CONTENT
    FROM ANNUAL_REPORTS WHERE REPORT_CONTENT IS NOT NULL
);

!print 'Cortex Search services created.'

-- ============================================================================
-- STEP 5: Verify Setup
-- ============================================================================
!print 'Step 5: Verifying setup...'

-- Show created objects
SHOW TABLES IN SCHEMA FINANCIAL_RESEARCH.EQUITY_RESEARCH;
SHOW CORTEX SEARCH SERVICES IN SCHEMA FINANCIAL_RESEARCH.EQUITY_RESEARCH;
SHOW STAGES IN SCHEMA FINANCIAL_RESEARCH.EQUITY_RESEARCH;

-- Test Cortex functions
SELECT SNOWFLAKE.CORTEX.COMPLETE('llama3.1-8b', 'Say hello in one word') as test_llm;

!print '============================================'
!print 'Setup complete!'
!print ''
!print 'Next steps:'
!print '1. Upload semantic model: PUT file://config/financial_research_semantic_model.yaml @SEMANTIC_MODELS AUTO_COMPRESS=FALSE;'
!print '2. Load sample data: Run files in data/ directory'
!print '3. Configure app: Update config.py with your connection details'
!print '4. Run app: docker-compose up -d'
!print '============================================'
